config/routes.rb
Rails.application.routes.draw do
 


  resources :districts
  resources :payments
  get 'searches/search'

  get 'searches/found'

  get 'searches/lost'

  resources :transactions
  resources :accounts
 get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
get 'notifications', to: 'notifications#index'
  resources :lostitems
  resources :types
  resources :plans
  captcha_route
  resources :areas
  resources :counties
post 'scrape' => 'accounts#scrape', as: :scrape
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions' }

  match '/users/:id',     to: 'users#show',       via: 'pacth' 
  match '/users/:id',     to: 'users#show',       via: 'get'
  match '/users/:id/edit',     to: 'users#edit',       via: 'get'
  match '/users',   to: 'users#index',   via: 'get'
  match '/user/',   to: 'users#update',   via: 'patch'
  match '/users/:id',   to: 'users#update',   via: 'patch'
  match '/users.:id',   to: 'users#update',   via: 'put'

devise_scope :user do
  root "pages#welcome" 
end
get "/admin", to: "pages#welcome"
get "/choose_plan", to: "users#edit"
get "/profile", to: "users#show"
get "/searches", to: "searches#search"
get "/found", to: "searches#found"
get "/lost", to: "searches#lost"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/models/agentr.rb
class Agentr < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :county
end

app/models/county.rb
class County < ApplicationRecord
	has_many :users
	has_many :areas
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
	belongs_to :user
end

app/models/lostid_detail.rb
class LostidDetail < ApplicationRecord
end

app/models/lostitem.rb
class Lostitem < ApplicationRecord
  belongs_to :type
  belongs_to :county
  belongs_to :user
   mount_uploader :picture_front, PictureUploader
    mount_uploader :picture_back, PictureUploader
    validates_uniqueness_of :id_number
 def self.search(search)
  if search
     where('id_number LIKE ?', "%#{search}%")
  else
    all
  end
end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
	has_many :users
 
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :account
	 
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_easy_captcha
 
  before_create :build_default_account 
 belongs_to :plan
 has_many :lostitems
 belongs_to :county
 belongs_to :area
 has_many :histories
  has_many :usersfoundid_contacts
 has_one :account
 has_many :notifications, dependent: :destroy
 validates :first_name, presence: true
  validates :second_name, presence: true
  validates :idnumber, presence: true
  validates :email, presence: true
  validates :county_id, presence: true
  validates :area_id, presence: true
  validates :terms, presence: true
  validates :mobilenumber, presence: true, length: {minimum: 10, maximum: 10} 
  mount_uploader :picture, PictureUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :secure_validatable, :confirmable, :lockable
          attr_accessor :raw_address
geocoded_by :raw_address
after_validation -> {
  self.address = self.raw_address
  geocode
}, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }

after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                 if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }
                  
before_create do
  o = [('1'..'9'), ('A'..'Z')].map(&:to_a).flatten
    self.user_code ||=  (0...5).map { o[rand(o.length)] }.join

  end



def build_default_account  
  build_account
  true
end  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:from_id, :to_id, :deposit, :withdrawal, :amount)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_id %>
    <%= f.number_field :from_id %>
  </div>

  <div class="field">
    <%= f.label :to_id %>
    <%= f.number_field :to_id %>
  </div>

  <div class="field">
    <%= f.label :deposit %>
    <%= f.check_box :deposit %>
  </div>

  <div class="field">
    <%= f.label :withdrawal %>
    <%= f.check_box :withdrawal %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Deposit</th>
      <th>Withdrawal</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.from_id %></td>
        <td><%= transaction.to_id %></td>
        <td><%= transaction.deposit %></td>
        <td><%= transaction.withdrawal %></td>
        <td><%= transaction.amount %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @transaction.from_id %>
</p>

<p>
  <strong>To:</strong>
  <%= @transaction.to_id %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @transaction.deposit %>
</p>

<p>
  <strong>Withdrawal:</strong>
  <%= @transaction.withdrawal %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>