config/routes.rb
Rails.application.routes.draw do
 


  resources :districts
  resources :payments
  get 'searches/search'

  get 'searches/found'

  get 'searches/lost'

  resources :transactions
  resources :accounts
 get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
get 'notifications', to: 'notifications#index'
  resources :lostitems
  resources :types
  resources :plans
  captcha_route
  resources :areas
  resources :counties
post 'scrape' => 'accounts#scrape', as: :scrape
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions' }

  match '/users/:id',     to: 'users#show',       via: 'pacth' 
  match '/users/:id',     to: 'users#show',       via: 'get'
  match '/users/:id/edit',     to: 'users#edit',       via: 'get'
  match '/users',   to: 'users#index',   via: 'get'
  match '/user/',   to: 'users#update',   via: 'patch'
  match '/users/:id',   to: 'users#update',   via: 'patch'
  match '/users.:id',   to: 'users#update',   via: 'put'

devise_scope :user do
  root "pages#welcome" 
end
get "/admin", to: "pages#welcome"
get "/choose_plan", to: "users#edit"
get "/profile", to: "users#show"
get "/searches", to: "searches#search"
get "/found", to: "searches#found"
get "/lost", to: "searches#lost"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/models/agentr.rb
class Agentr < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :county
end

app/models/county.rb
class County < ApplicationRecord
	has_many :users
	has_many :areas
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/foundid_detail.rb
class FoundidDetail < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
	belongs_to :user
end

app/models/lostid_detail.rb
class LostidDetail < ApplicationRecord
end

app/models/lostitem.rb
class Lostitem < ApplicationRecord
  belongs_to :type
  belongs_to :county
  belongs_to :user
   mount_uploader :picture_front, PictureUploader
    mount_uploader :picture_back, PictureUploader
    validates_uniqueness_of :id_number
 def self.search(search)
  if search
     where('id_number LIKE ?', "%#{search}%")
  else
    all
  end
end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
	has_many :users
 
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :account
	 
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_easy_captcha
 
  before_create :build_default_account 
 belongs_to :plan
 has_many :lostitems
 belongs_to :county
 belongs_to :area
 has_many :histories
  has_many :usersfoundid_contacts
 has_one :account
 has_many :notifications, dependent: :destroy
 validates :first_name, presence: true
  validates :second_name, presence: true
  validates :idnumber, presence: true
  validates :email, presence: true
  validates :county_id, presence: true
  validates :area_id, presence: true
  validates :terms, presence: true
  validates :mobilenumber, presence: true, length: {minimum: 10, maximum: 10} 
  mount_uploader :picture, PictureUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :secure_validatable, :confirmable, :lockable
          attr_accessor :raw_address
geocoded_by :raw_address
after_validation -> {
  self.address = self.raw_address
  geocode
}, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }

after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                 if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }
                  
before_create do
  o = [('1'..'9'), ('A'..'Z')].map(&:to_a).flatten
    self.user_code ||=  (0...5).map { o[rand(o.length)] }.join

  end



def build_default_account  
  build_account
  true
end  
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
    
  
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :cost, :duration, :support, :posts, :admin_panel, :lost_id_alerts, :reported_id_alerts)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/plans/_form.html.erb
<%= form_for(plan) do |f| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>
<div class="field">
    <%= f.label :number_of_posts_monthly %>
    <%= f.text_field :posts %>
  </div>
  <div class="field">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>

  <div class="field">
    <%= f.label :support %>
    <%= f.check_box :support %>
  </div>

  <div class="field">
    <%= f.label :admin_panel %>
    <%= f.check_box :admin_panel %>
  </div>

  <div class="field">
    <%= f.label :lost_id_alerts %>
    <%= f.check_box :lost_id_alerts %>
  </div>

  <div class="field">
    <%= f.label :reported_id_alerts %>
    <%= f.check_box :reported_id_alerts %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cost</th>
      <th>Duration</th>
      <th>Support</th>
      <th>Admin panel</th>
      <th>Lost id alerts</th>
      <th>Reported id alerts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= plan.cost %></td>
        <td><%= plan.duration %></td>
        <td><%= plan.support %></td>
        <td><%= plan.admin_panel %></td>
        <td><%= plan.lost_id_alerts %></td>
        <td><%= plan.reported_id_alerts %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'plans/form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @plan.cost %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @plan.duration %>
</p>

<p>
  <strong>Support:</strong>
  <%= @plan.support %>
</p>

<p>
  <strong>Admin panel:</strong>
  <%= @plan.admin_panel %>
</p>

<p>
  <strong>Lost id alerts:</strong>
  <%= @plan.lost_id_alerts %>
</p>

<p>
  <strong>Reported id alerts:</strong>
  <%= @plan.reported_id_alerts %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>