config/routes.rb
Rails.application.routes.draw do
 


  resources :districts
  resources :payments
  get 'searches/search'

  get 'searches/found'

  get 'searches/lost'

  resources :transactions
  resources :accounts
 get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
get 'notifications', to: 'notifications#index'
  resources :lostitems
  resources :types
  resources :plans
  captcha_route
  resources :areas
  resources :counties
post 'scrape' => 'accounts#scrape', as: :scrape
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions' }

  match '/users/:id',     to: 'users#show',       via: 'pacth' 
  match '/users/:id',     to: 'users#show',       via: 'get'
  match '/users/:id/edit',     to: 'users#edit',       via: 'get'
  match '/users',   to: 'users#index',   via: 'get'
  match '/user/',   to: 'users#update',   via: 'patch'
  match '/users/:id',   to: 'users#update',   via: 'patch'
  match '/users.:id',   to: 'users#update',   via: 'put'

devise_scope :user do
  root "pages#welcome" 
end
get "/admin", to: "pages#welcome"
get "/choose_plan", to: "users#edit"
get "/profile", to: "users#show"
get "/searches", to: "searches#search"
get "/found", to: "searches#found"
get "/lost", to: "searches#lost"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/controllers/accounts_controller.rb
require 'net/http'
require 'net/https'
require 'uri'
require 'mpesa_connect'
require 'json'
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end
def scrape

  
 tmobilenumber = "#{current_user.mobilenumber}".to_i
 password = "lostitems2017"
 code = 307522
uri = URI('https://api.safaricom.co.ke/mpesa/b2c/v1/paymentrequest')

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
request = Net::HTTP::Get.new(uri)
request["accept"] = 'application/json'
request["content-type"] = 'application/json'
request["authorization"] = "Bearer q8gp53fdaYXQYxvCxJj2pl0Jjcsl"
request.body = { "InitiatorName" => "webcloud",
 "SecurityCredential" => Base64.encode64(["#{code}", "#{password}"].join),
  "CommandID" => "SalaryPayment",
  "Amount" => "#{current_user.account.balance}",
  "PartyA" => "307522",
  "PartyB"=>  "254#{tmobilenumber}",
  "Remarks" => "ok",
  'QueueTimeOutURL' => 'https://lostitems.co.ke:5000/b2c/queue',
  'ResultURL' => 'https://lostitems.co.ke:5000/b2c/result',
  "Occasion" => "ok"}.to_json

response = http.request(request)
puts request.body

puts response.body
end
  # GET /accounts/1
  # GET /accounts/1.json
  def show
  @notifications = current_user.notifications.order('created_at DESC').limit(3)
  @transactions = Transaction.where(to_id: current_user.id).order('created_at DESC').limit(5)
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def generateTokken
  uri = URI('https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials')
  http = Net::HTTP.start(uri.host, uri.port,
  :use_ssl => uri.scheme == 'https',
  :verify_mode => OpenSSL::SSL::VERIFY_NONE)



  request = Net::HTTP::Get.new uri.request_uri
  request.basic_auth 'PfLuMoTfVLgf6DGXb21fAD9J1O7Jjecc', 'Yxjer0vFxnBldjyZ'

  response = http.request request # Net::HTTPResponse object
 puts token = JSON.parse(response.body)['access_token']

end
  private
   #Generate mpesa token
   
  #STK Push
  def paybc

uri = URI('https://api.safaricom.co.ke/mpesa/b2c/v1/paymentrequest')

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

request = Net::HTTP::Get.new(uri)
request["accept"] = 'application/json'
request["content-type"] = 'application/json'
request["authorization"] = "Bearer #{generateTokken}"
request.body = "{\"InitiatorName\":\" current_user.name\",
  \"SecurityCredential\":\" \",
  \"CommandID\":\"SalaryPayment \",
  \"Amount\":\"1000\",
  \"PartyA\":\"307552 \",
  \"PartyB\":\"@current_user.phone_number\",
  \"Remarks\":\" ok\",
  \"QueueTimeOutURL\":\"http://your_timeout_url\",
  \"ResultURL\":\"http://your_result_url\",
  \"Occasion\":\" ok\"}"

response = http.request(request)
puts response.body
    
  end
 
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :balance, :meta, :meta_name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :balance %>
    <%= f.text_field :balance %>
  </div>

  <div class="field">
    <%= f.label :meta %>
    <%= f.check_box :meta %>
  </div>

  <div class="field">
    <%= f.label :meta_name %>
    <%= f.text_field :meta_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Balance</th>
      <th>Meta</th>
      <th>Meta name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.user %></td>
        <td><%= account.balance %></td>
        <td><%= account.meta %></td>
        <td><%= account.meta_name %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<%= render 'pages/header' %>
<%=render 'pages/leftbar'%>
<div class="container account-section">
<h2>Your Account</h2>
<div class="col-md-3">
<p>
  <strong>Current Balance</strong><br>
  Ksh <%= @account.balance %>
</p>
</div>
<p>
<div class="col-md-3">
  <strong>Last Transaction Status</strong><br>
  <%if @account.meta == true %> Success <%else%> Failed <%end%>
</p>
</div>
<div class="col-md-3">
<p>
  <strong>Type of Last Transaction</strong><br>
  <%= @account.meta_name %>
</p>

</div>
<div class="col-md-3">
<p>
  <strong>Account Options</strong><br>
<li class='btn btn-sm btn-warning'><%= link_to "Refresh" %></li>
<%= button_to 'Withdraw', scrape_path, class: 'btn btn-sm btn-info' %>

</div>
</div>
<div class="container transactions-section" style="background: white; margin-top: 10px; font-size: 14px; overflow-x:auto">
<p id="notice"><%= notice %></p>

<h2>Your account history</h2>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Transaction type</th>
      <th>Amount</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.from_id %></td>
        <td><%if transaction.deposit = 1 %>Deposit<%else%> Withdrawal<%end%></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>